# Database settings.
# NOTE: these value will be overwritten by environment variables in the ProcFile
database:
  driverClass: org.mariadb.jdbc.Driver
  user: myuser
  password: mypassword
  url: myurl

swagger:
  schemes:
  - https
  - http
  resourcePackage: com.sdua.api.resource
  uriPrefix: /root/path
  title: Software Developement Utility app API Endpoints
  description: This is the listing of all the API endpoints of Software Developement Utility app back end. It lists resource details, operations supported, access methods and request/response format.
server:
  rootPath: /root/path
  applicationConnectors:
      - type: http
        port: 8080
#      - type: https
#       port: 8443
#        keyStorePath: example.keystore
#        keyStorePassword: example
#        validateCerts: false
#  adminConnectors:
#      - type: http
#        port: 8081
#      - type: https
#        port: 8444
#        keyStorePath: example.keystore
#        keyStorePassword: example
#        validateCerts: false

config:
  allowedOrigin: all
  appBaseUrl: /hot/url